preserved_cycles: 2
blocks_per_cycle: 8
blocks_per_commitment: 4
blocks_per_roll_snapshot: 4
blocks_per_voting_period: 64
time_between_blocks:
  - "20"
  - "10"
endorsers_per_block: 256
hard_gas_limit_per_operation: "1040000"
hard_gas_limit_per_block: "5200000"
proof_of_work_threshold: "70368744177663"
tokens_per_roll: "8000000000"
seed_nonce_revelation_tip: "125000"
origination_size: 257
block_security_deposit: "640000000"
endorsement_security_deposit: "2500000"
baking_reward_per_endorsement:
  - "78125"
  - "11719"
endorsement_reward:
  - "78125"
  - "52083"
cost_per_byte: "250"
hard_storage_limit_per_operation: "60000"
quorum_min: 2000
quorum_max: 7000
min_proposal_quorum: 500
initial_endorsers: 192
delay_per_missing_endorsement: "2"
liquidity_baking_escape_ema_threshold: 666667
liquidity_baking_subsidy: '2500000'
liquidity_baking_sunset_level: 10000000
minimal_block_delay: '5'
